module.exports = {
  apps: [
    // ── 微服务 ──────────────────────────────────────────
    {
      name: "rag-gateway",
      script: "services/gateway.py",
      interpreter: ".venv/Scripts/python.exe",
      cwd: "D:/minerU_local",
      env: {
        PYTHONUTF8: "1",
        PYTHONIOENCODING: "utf-8",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/gateway-error.log",
      out_file: "./logs/gateway-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
    {
      name: "rag-doc",
      script: "services/doc_service.py",
      interpreter: ".venv/Scripts/python.exe",
      cwd: "D:/minerU_local",
      env: {
        MINERU_DEVICE_MODE: "cuda",
        RAG_MINERU_MODE: "local",
        # RAG_MINERU_MODE: "api",              # 切换为 MinerU 云端 API
        # RAG_MINERU_API_TOKEN: "your-token", # API token（mineru.net 获取）
        PYTHONUTF8: "1",
        PYTHONIOENCODING: "utf-8",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/doc-error.log",
      out_file: "./logs/doc-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
    {
      name: "rag-vector",
      script: "services/vector_service.py",
      interpreter: ".venv/Scripts/python.exe",
      cwd: "D:/minerU_local",
      env: {
        PYTHONUTF8: "1",
        PYTHONIOENCODING: "utf-8",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/vector-error.log",
      out_file: "./logs/vector-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
    {
      name: "rag-reranker",
      script: "services/reranker_service.py",
      interpreter: ".venv/Scripts/python.exe",
      cwd: "D:/minerU_local",
      env: {
        PYTHONUTF8: "1",
        PYTHONIOENCODING: "utf-8",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/reranker-error.log",
      out_file: "./logs/reranker-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
    {
      name: "rag-llm",
      script: "services/llm_service.py",
      interpreter: ".venv/Scripts/python.exe",
      cwd: "D:/minerU_local",
      env: {
        PYTHONUTF8: "1",
        PYTHONIOENCODING: "utf-8",
      },
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "./logs/llm-error.log",
      out_file: "./logs/llm-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
    // ── 前端 ────────────────────────────────────────────
    {
      name: "rag-frontend",
      script: "node_modules/vite/bin/vite.js",
      cwd: "D:/minerU_local/frontend",
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      error_file: "../logs/frontend-error.log",
      out_file: "../logs/frontend-out.log",
      merge_logs: true,
      max_size: "50M",
      retain: 10,
    },
  ],
};
